### ISSUE TITLE
On fait quoi ?

### ISSUE THREAD

**Issue by JeanRibes** [BdEINSALyon/billevent#1]
# Requête d'organisatoin générale
Comment allons-nous organiser le logiciel ?
J'ai un peu du mal à définir ce que je dois faire ...
Est-ce qu'on fait des mini-serveurs qui communiquent par API REsT ? des ensemble de fichiers contenant classes et fonction à intégrer dans le serveur Django ?
En fait je sais pas où commencer, ni dans quel but d'utilisation écrire mon code !

Voilà .... 
P.S. : j'ai pas du tout besoin d'une réponse immédiate, je compte pas spécialement travailler sur le projet en semaine

**Comment by al26p** [comment]
Perso, je n'y travaillerai pas trop jusqu'à lundi prochain (IE Physique oups) 
Après tu peux jeter un coup d'oeuil sur modèles qui ont été faits, donner ton avis dessus. 
 Sinon @PhilippeGeek ?

**Comment by PhilippeVienne** [comment]
L'application billevent est monholitique et se découpe en application Django. Les différentes parties de l'application peuvent accéder aux modèles des autres. Les modèles doivent s'assurer d'être utilisé correctement.
Sur Mercanet, il me faut une page où je rentre un montant et une raison (#Commande) et je suis redirigé sur la BNP pour payé. Après mon paiement le site me le confirme.

**Comment by al26p** [comment]
Bonsoir bonsoir !
@PhilippeGeek Où en est la communication avec la BNP ? 
@hugnata @PhilippeGeek Faudra voir les api, conclure le truc. Plus mettre à jour le schéma relationnel qui, a priori, ne correspondrait plus à ce qui est en place réellement. 
@Nornort si tu as fini les tickets comme tu m'as dit, en attendant qu'on revoit ça ensemble, tu peux peut être essayer de voir avec hugo. Il saura t'éclairer avec le taff qui a été fait avec REST et django en général. 

Pour tout le monde, on se voit jeudi pour une sacrée session code
