### ISSUE TITLE
Erreur pendant le lancement du manage.py

### ISSUE THREAD

**Issue by hreymond** [BdEINSALyon/billevent#3]
Salut !

Quand j'essaye de faire n'importe quelle commande à l'aide de manage.py (En l’occurrence runserver et makemigrations) je reçoit un erreur qui semble liée à une ambiguïté dans les models qui apparait pendant les system checks.
ça a quelque chose à voir avec les relations

Pour info:
- Je suis sur la branche feature/mercanet
- J'utilise python 3.6.3
- Je passe par la console windows

C'est quoi le site pour héberger des logs déja ? Comme je l'ai pas retrouvé je vous le met en dessous...

Le log est ici 

`Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x0000000004034AE8>
Traceback (most recent call last):
  File "H:\Python\lib\site-packages\django\utils\autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "H:\Python\lib\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "H:\Python\lib\site-packages\django\core\management\base.py", line 405, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
api.Option.event: (fields.E304) Reverse accessor for 'Option.event' clashes with reverse accessor for 'Product.event'.
	HINT: Add or change a related_name argument to the definition for 'Option.event' or 'Product.event'.
api.Option.event: (fields.E305) Reverse query name for 'Option.event' clashes with reverse query name for 'Product.event'.
	HINT: Add or change a related_name argument to the definition for 'Option.event' or 'Product.event'.
api.PricingRule.pricings: (fields.E300) Field defines a relation with model 'Pricing', which is either not installed, or is abstract.
api.PricingRule.pricings: (fields.E307) The field api.PricingRule.pricings was declared with a lazy reference to 'api.pricing', but app 'api' doesn't provide model 'pricing'.
api.PricingRule_pricings.pricing: (fields.E307) The field api.PricingRule_pricings.pricing was declared with a lazy reference to 'api.pricing', but app 'api' doesn't provide model 'pricing'.
api.Product.event: (fields.E304) Reverse accessor for 'Product.event' clashes with reverse accessor for 'Option.event'.
	HINT: Add or change a related_name argument to the definition for 'Product.event' or 'Option.event'.
api.Product.event: (fields.E305) Reverse query name for 'Product.event' clashes with reverse query name for 'Option.event'.
	HINT: Add or change a related_name argument to the definition for 'Product.event' or 'Option.event'.

System check identified 7 issues (0 silenced).

**Comment by JeanRibes** [comment]
j'ai exactement les mêmes erreurs, et je ne pense pas que ce soit lié à la branche mercanet, mais plutôt au code dans le dossier api

**Comment by PhilippeVienne** [comment]
Solved
