### ISSUE TITLE
Ajout de catégorie de produit ? 

### ISSUE THREAD

**Issue by al26p** [BdEINSALyon/billevent#6]
Bonsoir, 
On peut créer des produits, je me demande si ça ne serait pas pertinent qu'il soit également possible de les attribuer à une catégorie de produit. 
ex : catégorie Pack Nuité ou Pack soirée et que sous ces catégories on ait les différents produits; 

Faites moi vos retours ;)

**Comment by Crocmagnon** [comment]
J'ai pas compris
