### ISSUE TITLE
[MERDE] Verif Mercanet

### ISSUE THREAD

**Issue by al26p** [BdEINSALyon/billevent#7]
Commande validée même si pas de paiment.

**Comment by JeanRibes** [comment]
sur quelle valeur te bases-tu ? 
dans la base de données Transactions BNP, le champ ``Status de la transaction`` indique la réponse Mercanet; c'est ce champ-la qu'il faut regarder.
Si il a merdé, là le bug vient peut-être pas de nous

après j'ai pas suivi comment la validation est faite en interne, donc si ça se trouve c'est juste un problème de variable

**Comment by JeanRibes** [comment]
malheuresement, je n'arrive pas à provoquer d'autres erreurs que Refus 3D Secure, mais dans la base de donnés "Transaction avec la BNP", j'ai le status correct
vérifie la configuration du serveur de test

**Comment by Crocmagnon** [comment]
D'après @PhilippeGeek c'est résolu.
